### ISSUE TITLE
Downloads tracking doesn't track all downloads

### ISSUE THREAD

**Issue by arterrey** [collective/collective.googleanalytics#19]
Currently the download tracking plugin works by running jquery on page load to put an event handler for when you click on links that look like download links (such as those ending in .pdf etc).
This has several problems
- direct inbound links such as from google search results won't be tracked
- ajax loaded links such as from eea.facetednavigation or live search, won't be tracked
- determining if a link results in a download is heuristic. 

There are few options to potentially solve this
1. change the way direct file downloads work to display a html page temporarily which executes some JS to register the event. Care would have to be taken to ensure google stiff indexes documents correctly.
2.  detect a DOM change and update any new links with the click event required for GA. This only fixes the AJAX problem
3. do server-side call to UA to register the a event or virtual page event, each time a direct download is triggered. This can be done using async thread outside the transaction to avoid slowing down the request.

We propose to implement 3 since its the only solution that seems to work for all cases. This will likely involve switching to universal analytics and perhaps setting our own tracking ids.

**Comment by djay** [comment]
@rbruch I never saw this reply. sorry. 
- Compatible. Events is a poor way to do things. Now days you can do proper hits via the api which is better than using Events I believe and trumps backwards compatibility.
- Not sure if a direct download who never visited the site would get counted or not since its possible some kind of cookie has to get set before to work out the tracking code, or perhaps it would get counted but not linked to other browsing if they came to the site after. I think a direct download should get counted as a visit though
- This would have to be worked out. Would need to be careful to only include serverside hits that wouldn't be counted as a clientside hit... or perhaps there is some tracking system that allows GA to not double count it.
